glory_wechat_server:
    path:   /wechat
    defaults: { _controller: GloryWechatBundle:Server:message }

glory_wechat_qrcode:
    path:   /wechat/qrcode/{code}
    defaults: { _controller: GloryWechatBundle:Qrcode:forever }
glory_wechat_qrcode_temp:
    path:   /wechat/qrcode/{code}/temp
    defaults: { _controller: GloryWechatBundle:Qrcode:temporary }

glory_wechat_pay_qrcode:
    path:   /wechat/pay/{id}
    defaults: { _controller: GloryWechatBundle:Payment:qrcode }

glory_wechat_admin_user:
    path: /admin/wechat/user
    defaults: { _controller: GloryWechatBundle:User:index }

glory_wechat_js:
    path: /wechat/js
    defaults: { _controller: GloryWechatBundle:Js:config }