glory_wechat_server:
    path:   /wechat
    defaults: { _controller: GloryWechatBundle:Server:message }

glory_wechat_qrcode:
    path:   /wechat/qrcode/{code}
    defaults: { _controller: GloryWechatBundle:Qrcode:forever }
glory_wechat_qrcode_temp:
    path:   /wechat/qrcode/{code}/temp
    defaults: { _controller: GloryWechatBundle:Qrcode:temporary }

glory_wechat_pay_qrcode:
    path:   /wechat/pay/{id}
    defaults: { _controller: GloryWechatBundle:Payment:qrcode }