parameters:
    #wechat.app.class: EasyWeChat\Foundation\Application
    wechat.app.class: Glory\Bundle\WechatBundle\Wechat\Application

services:
    wechat.app:
        class: %wechat.app.class%
        arguments: [@service_container]
    
    glory_wechat.listener:
        class: Glory\Bundle\WechatBundle\EventListener\ServerListener
        arguments: [@service_container]
        tags:
            -  { name: kernel.event_subscriber }
