parameters:
    #wechat.app.class: EasyWeChat\Foundation\Application
    wechat.app.class: Glory\Bundle\WechatBundle\Wechat\Application
    wechat.app.class: Glory\Bundle\WechatBundle\Entity\WechatManager

services:
    glory_wechat.app:
        class: %wechat.app.class%
        arguments: [@service_container]
    
    glory_wechat.listener:
        class: Glory\Bundle\WechatBundle\EventListener\ServerListener
        arguments: [@service_container]
        tags:
            -  { name: kernel.event_subscriber }

    glory_wechat.manager:
        class:  %wechat.manager.class%
        arguments: [@service_container]