parameters:
    #wechat.app.class: EasyWeChat\Foundation\Application
    wechat.app.class: Glory\Bundle\WechatBundle\Wechat\Application

services:
    wechat.app:
        class: %wechat.app.class%
        arguments: [@service_container]
    
    glory_theme.listener:
        class: Glory\Bundle\WechatBundle\EventSubscriber\ServerSubscriber
        arguments: [@service_container]
        tags:
            -  { name: kernel.event_subscriber }
        
    wechat.message.text:
        class: Overtrue\Wechat\Messages\Text
    wechat.message.image:
        class: Overtrue\Wechat\Messages\Image
    wechat.message.voice:
        class: Overtrue\Wechat\Messages\Voice
    wechat.message.video:
        class: Overtrue\Wechat\Messages\Video
    wechat.message.mpvideo:
        class: Overtrue\Wechat\Messages\MpVideo
    wechat.message.music:
        class: Overtrue\Wechat\Messages\Music
    wechat.message.news:
        class: Overtrue\Wechat\Messages\News
    wechat.message.transfer:
        class: Overtrue\Wechat\Messages\Transfer
    wechat.message.news_item:
        class: Overtrue\Wechat\Messages\NewsItem
    wechat.message.mp_news:
        class: Overtrue\Wechat\Messages\MpNews
    wechat.message.wxcard:
        class: Overtrue\Wechat\Messages\Wxcard